[package]
name = "estimator-warehouse"
version = "0.0.0"
# Please update rust-toolchain.toml as well when changing version here:
edition = "2021"
publish = false
rust-version = "1.56.0"

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = "=3.0.0-beta.2"
reqwest = {version = "0.11", features = ["blocking", "json"]}
rusqlite = {version = "0.27", features = ["bundled", "chrono"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
